import NestCore
import NestData
import SwiftUI

/// One-tap pediatrician report: date range, daily totals table, the Day clock chart, diaper
/// colour log and notes, as a US Letter PDF for AirDrop, Messages or print.
@MainActor
enum ReportRenderer {
  static let pageSize = CGSize(width: 612, height: 792)

  static func render(
    baby: Baby, history: History, notes: [BabyNote], questions: [Question] = [], days: Int, now: Date = Date()
  ) throws -> URL {
    // Start at the birth, not at the range: no rows of zeros for days before she was born.
    let stats = DailyStatsBuilder.trimmed(
      DailyStatsBuilder.build(history: history, days: days, now: now), birth: baby.birthDate)
    let start = stats.first?.day ?? now
    let stools = history.diapers
      .filter { $0.stoolColor != nil && $0.occurredAt >= start }
      .sorted { $0.occurredAt > $1.occurredAt }
    let reportNotes = notes.filter { $0.occurredAt >= start }.sorted { $0.occurredAt > $1.occurredAt }

    var pages: [AnyView] = [
      AnyView(SummaryPage(baby: baby, stats: stats, history: history, now: now))
    ]
    if !questions.isEmpty {
      pages.append(AnyView(QuestionsPage(baby: baby, questions: questions)))
    }
    pages.append(AnyView(DayClockPage(baby: baby, history: history, days: stats.count, now: now)))
    pages.append(AnyView(LogPage(baby: baby, stools: stools, notes: reportNotes)))

    let name = "\(baby.name.isEmpty ? "Baby" : baby.name) report \(now.formatted(.iso8601.year().month().day())).pdf"
    let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
    var box = CGRect(origin: .zero, size: pageSize)
    guard let context = CGContext(url as CFURL, mediaBox: &box, nil) else {
      throw CocoaError(.fileWriteUnknown)
    }
    for page in pages {
      let renderer = ImageRenderer(
        content: page.frame(width: pageSize.width, height: pageSize.height).environment(\.colorScheme, .light))
      renderer.proposedSize = ProposedViewSize(pageSize)
      renderer.render { _, draw in
        context.beginPDFPage(nil)
        draw(context)
        context.endPDFPage()
      }
    }
    context.closePDF()
    return url
  }
}

private struct PageFrame<Content: View>: View {
  let baby: Baby
  let title: String
  @ViewBuilder var content: Content

  var body: some View {
    VStack(alignment: .leading, spacing: 14) {
      HStack(alignment: .firstTextBaseline) {
        Text(baby.name.isEmpty ? "Baby" : baby.name).font(.title.bold())
        if let birth = baby.birthDate {
          Text("born \(birth.formatted(date: .abbreviated, time: .omitted)) · \(AgeMath.label(birth: birth, now: Date()))")
            .foregroundStyle(.secondary)
        }
        Spacer()
        Text(title).font(.headline)
      }
      Divider()
      content
      Spacer(minLength: 0)
      Text("Generated by Nest. Tracked by parents; not a medical record.")
        .font(.caption2)
        .foregroundStyle(.secondary)
    }
    .padding(40)
    .background(Color.white)
    .foregroundStyle(.black)
  }
}

private struct SummaryPage: View {
  let baby: Baby
  let stats: [DayStats]
  let history: History
  let now: Date

  var body: some View {
    PageFrame(baby: baby, title: "Daily totals") {
      if let first = stats.first?.day {
        Text("\(first.formatted(date: .abbreviated, time: .omitted)) – \(now.formatted(date: .abbreviated, time: .omitted))")
          .font(.subheadline)
      }
      Grid(alignment: .trailing, horizontalSpacing: 10, verticalSpacing: 4) {
        GridRow {
          Text("Day").gridColumnAlignment(.leading)
          Text("Feeds")
          Text("Bottle")
          Text("Nursing")
          Text("Sleep")
          Text("Longest sleep")
          Text("Wet")
          Text("Dirty")
        }
        .font(.caption.weight(.semibold))
        Divider()
        ForEach(stats.reversed()) { day in
          GridRow {
            Text(day.day.formatted(.dateTime.weekday(.abbreviated).month(.abbreviated).day()))
              .gridColumnAlignment(.leading)
            Text("\(day.feedCount)")
            Text(day.bottleMl > 0 ? Volume.format(ml: day.bottleMl, unit: baby.unit) : "–")
            Text(day.nursingLeft + day.nursingRight > 0 ? Durations.format(day.nursingLeft + day.nursingRight) : "–")
            Text(duration(day.sleepTotal))
            Text(duration(day.longestSleep))
            Text("\(day.wetCount)")
            Text("\(day.dirtyCount)")
          }
          .font(.caption.monospacedDigit())
        }
        if let average = DailyStatsBuilder.averages(stats, birth: baby.birthDate) {
          Divider()
          GridRow {
            Text("Average").gridColumnAlignment(.leading)
            Text(average.feeds.formatted(.number.precision(.fractionLength(1))))
            Text(average.bottleMl > 0 ? Volume.format(ml: average.bottleMl, unit: baby.unit) : "–")
            Text(duration(average.nursing))
            Text(duration(average.sleep))
            Text("")
            Text(average.wet.formatted(.number.precision(.fractionLength(1))))
            Text(average.dirty.formatted(.number.precision(.fractionLength(1))))
          }
          .font(.caption.monospacedDigit().weight(.semibold))
        }
      }
      if let average = DailyStatsBuilder.averages(stats, birth: baby.birthDate) {
        Text("Average is per whole day over \(average.days) days, leaving out today and the day of birth.")
          .font(.caption2)
          .foregroundStyle(.secondary)
      }
      let totals = RollingTotals.compute(history: history, since: now.addingTimeInterval(-86_400), now: now)
      Text("Last 24 h: \(totals.feeds) feeds, \(Volume.format(ml: totals.bottleMl, unit: baby.unit)) by bottle, \(Durations.format(totals.nursing)) nursing, \(Durations.format(totals.sleep)) sleep, \(totals.wet) wet, \(totals.dirty) dirty.")
        .font(.footnote)
    }
  }
}

/// "–" instead of "0 s" for days with nothing.
private func duration(_ seconds: TimeInterval) -> String {
  seconds > 0 ? Durations.format(seconds) : "–"
}

private struct DayClockPage: View {
  let baby: Baby
  let history: History
  let days: Int
  let now: Date

  var body: some View {
    PageFrame(baby: baby, title: "Day clock") {
      Text("Each row is one day, midnight to midnight. Bars are sleep; dots are feeds (purple nursing, blue bottle); diamonds are diapers.")
        .font(.footnote)
      // Fewer days get taller rows, so the chart uses the page instead of hugging the top.
      DayClockChart(history: history, days: min(days, 30), now: now, rowHeight: min(46, 560 / CGFloat(max(1, min(days, 30)))))
    }
  }
}

/// What to ask, with room to write the answer by hand, and what was answered before.
private struct QuestionsPage: View {
  let baby: Baby
  let questions: [Question]

  private var open: [Question] { questions.filter { !$0.isDone } }
  private var answered: [Question] { questions.filter(\.isDone) }
  private var writingLines: Int { open.count <= 4 ? 3 : (open.count <= 7 ? 2 : 1) }

  var body: some View {
    PageFrame(baby: baby, title: "Questions for the doctor") {
      if !open.isEmpty {
        Text("To ask").font(.headline)
        ForEach(open.prefix(9)) { question in
          HStack(alignment: .top, spacing: 10) {
            Image(systemName: "square").font(.callout)
            VStack(alignment: .leading, spacing: 22) {
              Text(RichText(stored: question.body).attributed()).font(.callout)
              // Room to write the doctor's answer by hand: more lines when there are few questions.
              ForEach(0..<writingLines, id: \.self) { _ in
                Rectangle().fill(Color.black.opacity(0.18)).frame(height: 0.5)
              }
            }
          }
        }
        if open.count > 9 {
          Text("and \(open.count - 9) more in the app").font(.caption).foregroundStyle(.secondary)
        }
      }
      if !answered.isEmpty {
        Divider()
        Text("Already answered").font(.headline)
        ForEach(answered.prefix(6)) { question in
          VStack(alignment: .leading, spacing: 2) {
            Text(RichText(stored: question.body).attributed()).font(.caption.weight(.semibold))
            let answer = RichText(stored: question.answer)
            if !answer.isEmpty {
              Text(answer.attributed()).font(.caption).foregroundStyle(.secondary)
            }
          }
        }
        if answered.count > 6 {
          Text("and \(answered.count - 6) more in the app").font(.caption).foregroundStyle(.secondary)
        }
      }
    }
  }
}

private struct LogPage: View {
  let baby: Baby
  let stools: [DiaperRecord]
  let notes: [BabyNote]

  var body: some View {
    PageFrame(baby: baby, title: "Stool colours and notes") {
      Text("Stool colour log").font(.headline)
      if stools.isEmpty {
        Text("No stool colours recorded.").font(.caption)
      }
      ForEach(Array(stools.prefix(24).enumerated()), id: \.offset) { _, diaper in
        HStack {
          Circle().fill(diaper.stoolColor?.swatch ?? .clear).frame(width: 10, height: 10)
          Text(diaper.occurredAt.formatted(date: .abbreviated, time: .shortened)).monospacedDigit()
          Text(diaper.stoolColor?.title ?? "")
          if diaper.stoolColor?.isWorthACall(ageInDays: baby.birthDate.map { AgeMath.days(from: $0, to: diaper.occurredAt) }) == true {
            Text("· flagged").bold()
          }
        }
        .font(.caption)
      }
      Divider()
      Text("Notes").font(.headline)
      if notes.isEmpty {
        Text("No notes.").font(.caption)
      }
      ForEach(notes.prefix(20)) { note in
        Text("\(note.occurredAt.formatted(date: .abbreviated, time: .shortened)) — \(note.tag.map { "\($0.title): " } ?? "")\(note.text)")
          .font(.caption)
      }
    }
  }
}
