import NestCore
import NestData
import SwiftUI

/// One-tap pediatrician report: date range, daily totals table, the Day clock chart, diaper
/// colour log and notes, as a US Letter PDF for AirDrop, Messages or print.
@MainActor
enum ReportRenderer {
  static let pageSize = CGSize(width: 612, height: 792)

  static func render(baby: Baby, history: History, notes: [BabyNote], days: Int, now: Date = Date()) throws -> URL {
    let stats = DailyStatsBuilder.build(history: history, days: days, now: now)
    let start = stats.first?.day ?? now
    let stools = history.diapers
      .filter { $0.stoolColor != nil && $0.occurredAt >= start }
      .sorted { $0.occurredAt > $1.occurredAt }
    let reportNotes = notes.filter { $0.occurredAt >= start }.sorted { $0.occurredAt > $1.occurredAt }

    let pages: [AnyView] = [
      AnyView(SummaryPage(baby: baby, stats: stats, history: history, now: now)),
      AnyView(DayClockPage(baby: baby, history: history, days: days, now: now)),
      AnyView(LogPage(baby: baby, stools: stools, notes: reportNotes)),
    ]

    let name = "\(baby.name.isEmpty ? "Baby" : baby.name) report \(now.formatted(.iso8601.year().month().day())).pdf"
    let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
    var box = CGRect(origin: .zero, size: pageSize)
    guard let context = CGContext(url as CFURL, mediaBox: &box, nil) else {
      throw CocoaError(.fileWriteUnknown)
    }
    for page in pages {
      let renderer = ImageRenderer(
        content: page.frame(width: pageSize.width, height: pageSize.height).environment(\.colorScheme, .light))
      renderer.proposedSize = ProposedViewSize(pageSize)
      renderer.render { _, draw in
        context.beginPDFPage(nil)
        draw(context)
        context.endPDFPage()
      }
    }
    context.closePDF()
    return url
  }
}

private struct PageFrame<Content: View>: View {
  let baby: Baby
  let title: String
  @ViewBuilder var content: Content

  var body: some View {
    VStack(alignment: .leading, spacing: 14) {
      HStack(alignment: .firstTextBaseline) {
        Text(baby.name.isEmpty ? "Baby" : baby.name).font(.title.bold())
        if let birth = baby.birthDate {
          Text("born \(birth.formatted(date: .abbreviated, time: .omitted)) · \(AgeMath.label(birth: birth, now: Date()))")
            .foregroundStyle(.secondary)
        }
        Spacer()
        Text(title).font(.headline)
      }
      Divider()
      content
      Spacer(minLength: 0)
      Text("Generated by Nest. Tracked by parents; not a medical record.")
        .font(.caption2)
        .foregroundStyle(.secondary)
    }
    .padding(40)
    .background(Color.white)
    .foregroundStyle(.black)
  }
}

private struct SummaryPage: View {
  let baby: Baby
  let stats: [DayStats]
  let history: History
  let now: Date

  var body: some View {
    PageFrame(baby: baby, title: "Daily totals") {
      if let first = stats.first?.day {
        Text("\(first.formatted(date: .abbreviated, time: .omitted)) – \(now.formatted(date: .abbreviated, time: .omitted))")
          .font(.subheadline)
      }
      Grid(alignment: .trailing, horizontalSpacing: 10, verticalSpacing: 4) {
        GridRow {
          Text("Day").gridColumnAlignment(.leading)
          Text("Feeds")
          Text("Bottle")
          Text("Nursing")
          Text("Sleep")
          Text("Longest")
          Text("Wet")
          Text("Dirty")
        }
        .font(.caption.weight(.semibold))
        Divider()
        ForEach(stats.reversed()) { day in
          GridRow {
            Text(day.day.formatted(.dateTime.weekday(.abbreviated).month(.abbreviated).day()))
              .gridColumnAlignment(.leading)
            Text("\(day.feedCount)")
            Text(day.bottleMl > 0 ? Volume.format(ml: day.bottleMl, unit: baby.unit) : "–")
            Text(day.nursingLeft + day.nursingRight > 0 ? Durations.format(day.nursingLeft + day.nursingRight) : "–")
            Text(Durations.format(day.sleepTotal))
            Text(Durations.format(day.longestSleep))
            Text("\(day.wetCount)")
            Text("\(day.dirtyCount)")
          }
          .font(.caption.monospacedDigit())
        }
      }
      let totals = RollingTotals.compute(history: history, since: now.addingTimeInterval(-86_400), now: now)
      Text("Last 24 h: \(totals.feeds) feeds, \(Volume.format(ml: totals.bottleMl, unit: baby.unit)) by bottle, \(Durations.format(totals.nursing)) nursing, \(Durations.format(totals.sleep)) sleep, \(totals.wet) wet, \(totals.dirty) dirty.")
        .font(.footnote)
    }
  }
}

private struct DayClockPage: View {
  let baby: Baby
  let history: History
  let days: Int
  let now: Date

  var body: some View {
    PageFrame(baby: baby, title: "Day clock") {
      Text("Each row is one day, midnight to midnight. Bars are sleep; dots are feeds (purple nursing, blue bottle); diamonds are diapers.")
        .font(.footnote)
      DayClockChart(history: history, days: min(days, 30), now: now)
    }
  }
}

private struct LogPage: View {
  let baby: Baby
  let stools: [DiaperRecord]
  let notes: [BabyNote]

  var body: some View {
    PageFrame(baby: baby, title: "Stool colours and notes") {
      Text("Stool colour log").font(.headline)
      if stools.isEmpty {
        Text("No stool colours recorded.").font(.caption)
      }
      ForEach(Array(stools.prefix(24).enumerated()), id: \.offset) { _, diaper in
        HStack {
          Circle().fill(diaper.stoolColor?.swatch ?? .clear).frame(width: 10, height: 10)
          Text(diaper.occurredAt.formatted(date: .abbreviated, time: .shortened)).monospacedDigit()
          Text(diaper.stoolColor?.title ?? "")
          if diaper.stoolColor?.isWorthACall(ageInDays: baby.birthDate.map { AgeMath.days(from: $0, to: diaper.occurredAt) }) == true {
            Text("· flagged").bold()
          }
        }
        .font(.caption)
      }
      Divider()
      Text("Notes").font(.headline)
      if notes.isEmpty {
        Text("No notes.").font(.caption)
      }
      ForEach(notes.prefix(20)) { note in
        Text("\(note.occurredAt.formatted(date: .abbreviated, time: .shortened)) — \(note.tag.map { "\($0.title): " } ?? "")\(note.text)")
          .font(.caption)
      }
    }
  }
}
